# Site settings
title: photography student association
email: uhpsa.contact@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  welcome to the photography student association at the University of Houston
baseurl:  # the subpath of your site, e.g. /blog/
url:  "https://photography-student-association.github.io" # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  github_username

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/


